name: "Build static site"
on:
  push:
    branches: ["static-site"]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          bash -f ./build_static.sh
      
      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: website
          path: |
            ./dist/html/*
          retention-days: 7